### ISSUE TITLE
Please provide steps to integrate FCM in eclipse android project

### ISSUE THREAD

**Issue by rohitdroid** [dandar3/android-google-firebase-common#3]
I have added common, iid and messaging jar files also updated manifest accordingly. But application giving runtimeexception with class not found error.

**Comment by dandar3** [comment]
1. Remove everything you have added, all you need to have is your app project

2. Install Subversive plugin to Eclipse, restart Eclipse.
Recommeding latest build + SVNKit (Java based) instead of JavaHL (OS native binary)
https://polarion.plm.automation.siemens.com/products/svn/subversive/download

3. Import in Eclipse `android-google-firebase-messaging` using the video tutorial below:
https://github.com/dandar3/android-google-firebase-README
or manually using the instructions provided on the project page:
https://github.com/dandar3/android-google-firebase-messaging/tree/15.0.0
File > Import... > Team > Team Project Set > URL:
https://raw.githubusercontent.com/dandar3/android-google-firebase-messaging/15.0.0/.projectset

4. Add `android-google-firebase-messaging` as a Android Library dependecy to your project app (Properties > Android ...)

5. Enable manifest merger into your app project's `project.properties`
https://stackoverflow.com/a/11234525/308836

6. Rebuild + Deploy and let me know how it worked this time (Y) either here if succesful or if unsuccesful by email (see my profile) with more details / screenshots.

Notes: Manifest merger is not specified in this blog post, you can skip the part with manually updating your AndroidManifest.xml, see if this helps with the implementation:
https://dandar3.blogspot.com/2017/01/eclipse-integrating-firebase-messaging.html
